### ISSUE TITLE
 App Store 上的描述可能有病句等问题

### ISSUE THREAD

**Issue by YDX-2147483647** [BobH233/LexueSwiftUI#1]
例如 [App Store 上的“i乐学助手”](https://apps.apple.com/cn/app/i%E4%B9%90%E5%AD%A6%E5%8A%A9%E6%89%8B/id6468846337)第一句话就有以下若干问题。

> i乐学助手是为北京理工大学“乐学”提供服务的ios端手机app，具有增强的功能如“临近作业期限提醒”、“小组件显示最近日程”、“聚合全校消息通知”等功能，为北京理工大学的同学提供更方便的使用体验。

- > 具有增强的功能如……等功能

  建议改为“具有……等增强功能”或“具备的增强功能有……等”。

- > “临近作业期限提醒”、“小组件显示最近日程”、“聚合全校消息通知”

  按照 [GB/T 15834—2011 标点符号用法](https://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=22EA6D162E4110E752259661E1A0D0A8) 4.5.3.5，标有引号的并列成分之间通常不用顿号，像下面这样直接连接即可。

  > “临近作业期限提醒”“小组件显示最近日程”“聚合全校消息通知”

- > ios

  建议修改为“iOS”，因为我看你后面 iCloud 都按特殊大小写了。

- > 为北京理工大学的同学提供更方便的使用体验

  完全不必使用“使用体验”这种抽象名词，可直接这样说话。

  > 让北京理工大学的同学使用更方便

- > i乐学助手是为北京理工大学“乐学”提供服务的ios端手机app

  似乎应该给“同学”提供服务，而非给“乐学”提供服务？

注：以上恐怕有些吹毛求疵，如果你不喜欢，无妨直接关闭此议题。

**Comment by BobH233** [comment]
感谢感谢，我下一个版本的简介就修改。
