### ISSUE TITLE
同一课程多次考试成绩显示错误

### ISSUE THREAD

**Issue by FrzMtrsprt** [BobH233/LexueSwiftUI#2]
# 问题描述
在成绩查询页中，每个课程仅首次考试成绩显示正常，后续的重考/补考会被显示为首次考试的数据。同时，计算GPA、加权平均分时会重复计算同一课程每次考试的成绩。

# 当前行为
例如，如果我的成绩单如下：
|学期|课程名称|成绩|学分|
|-|-|-|-|
|学期1|课程A|80|2|
|学期1|课程B|40|1|
|学期2|课程B|80|1|

那么在应用中成绩单就会被显示为这样：
|学期|课程名称|成绩|学分|
|-|-|-|-|
|学期1|课程A|80|2|
|学期1|课程B|40|1|
|学期1|课程B|40|1|

实际的加权平均分应该为

$$ \frac{80\times2+80\times1}{2+1}=80$$

但目前应用中显示的加权平均分为

$$\frac{80\times2+40\times1+80\times1}{2+1+1}=70$$

# 预期行为
正确显示同一课程后续考试的成绩，并在计算GPA、加权平均分时只包含同一科目的最后一次考试成绩。
同时，可以考虑用不同颜色显示不被计入GPA、加权平均分的成绩。

**Comment by BobH233** [comment]
感谢您耐心的反馈，我会在有空的时候复现这个问题，尽量在下一个版本更新时解决这个问题。

**Comment by BobH233** [comment]
https://github.com/BobH233/LexueSwiftUI/commit/0c6520c70f1d5c555e3bd36c32b6e832666827e8
已修复，在即将上线的1.4版本即可体验到修复后的成绩查询功能

**Comment by FrzMtrsprt** [comment]
感谢开发者更新，更新1.4后，成绩能够显示正确了，但平均分和GPA的计算结果仍然和bit101的计算结果不同，计入了同一课程的所有成绩。

同时，不应计入成绩的课程的详情中并未出现[0c6520c](https://github.com/BobH233/LexueSwiftUI/commit/0c6520c70f1d5c555e3bd36c32b6e832666827e8)添加的“不计入分数”卡片，也没有被strikethrough。列表中只有其中一门补考科目的其中一次考试被标绿，加上“(补考)”，其他补考均被显示为正常考试。

**Comment by FrzMtrsprt** [comment]
我从bit101 api的/score?detail=true获得了查询成绩的response（删除了部分不相关的成绩），希望能帮助调试

[score.json](https://github.com/BobH233/LexueSwiftUI/files/13985176/score.json)

**Comment by BobH233** [comment]
> 我从bit101 api的/score?detail=true获得了查询成绩的response（删除了部分不相关的成绩），希望能帮助调试
> 
> [score.json](https://github.com/BobH233/LexueSwiftUI/files/13985176/score.json)

平均分我这边是剔除了同一门课程被划去的成绩的，理论上应该不会有问题。能加交流群我们详细谈谈么？[交流群](https://qm.qq.com/q/SjrrWAcNUa)

**Comment by BobH233** [comment]
> 感谢开发者更新，更新1.4后，成绩能够显示正确了，但平均分和GPA的计算结果仍然和bit101的计算结果不同，计入了同一课程的所有成绩。
> 
> 同时，不应计入成绩的课程的详情中并未出现[0c6520c](https://github.com/BobH233/LexueSwiftUI/commit/0c6520c70f1d5c555e3bd36c32b6e832666827e8)添加的“不计入分数”卡片，也没有被strikethrough。列表中只有其中一门补考科目的其中一次考试被标绿，加上“(补考)”，其他补考均被显示为正常考试。

发现了一处逻辑错误😂，现在这个版本只有在第二次查询成绩时才会显示正确的结果，我的失误... 我会在下个版本修复这个问题。

具体而言在 [ViewScoreView.swift](https://github.com/BobH233/LexueSwiftUI/blob/f77981b9ab9e15a7a9e96cb680f71f1e0f8a867a/LexueSwiftUI/Views/ScoreAnalyze/ViewScoreView.swift#L287) 这个地方，也就是没有命中缓存cookie的时候，我忘记加入处理函数“ProcessResitSituation”，导致本该被划去的课程没有被正确划去。

如果再次点击成绩查询，因为命中缓存cookie，所以会正确加载并计算分数。

**Comment by BobH233** [comment]
https://github.com/BobH233/LexueSwiftUI/commit/251aab615dee8f29101025948fba6fd2912b582f

现在应该没问题了

**Comment by FrzMtrsprt** [comment]
嗯是的，再次点进来的话标绿的课程确实被划掉了，但还有几门成绩既没有标绿也没有被划掉，我感觉是因为只匹配了“补考”没有匹配“重考”

**Comment by BobH233** [comment]
> 嗯是的，再次点进来的话标绿的课程确实被划掉了，但还有几门成绩既没有标绿也没有被划掉，我感觉是因为只匹配了“补考”没有匹配“重考”

是的，已经修改

https://github.com/BobH233/LexueSwiftUI/commit/9051f8265d21bc50f8ab7893d282c1b591d995e8

另外，你能参与TestFlight的内测吗，我可以将最新版本发到TestFlight上，然后你再看看还有问题没？

**Comment by FrzMtrsprt** [comment]
好的，怎么加入TestFlight呢？

**Comment by BobH233** [comment]
> 好的，怎么加入TestFlight呢？

https://testflight.apple.com/join/PSGEHyQE

**Comment by FrzMtrsprt** [comment]
更新到1.5后一切正常了

**Comment by BobH233** [comment]
> 更新到1.5后一切正常了

OK
